env:
    browser: true
    es6: true
extends:
    - "eslint:recommended"
    - "plugin:react/recommended"
    - "plugin:@typescript-eslint/eslint-recommended"
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    - react
    - "@typescript-eslint"
settings:
    react:
        version: "17"
rules:
    indent:
        - error
        - tab
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - always
    no-unused-vars:
        - off
    react/prop-types:
        - off
